import { AnalyzeResponse } from "./types";

export const SAMPLE_ANALYSIS_DATA: AnalyzeResponse = {
  github: {
    total_repos: 18,
    skills_detected: {
      Python: 14,
      FastAPI: 8,
      Docker: 6,
      TypeScript: 5,
      React: 4,
      PostgreSQL: 4,
      Redis: 3,
      pytest: 8,
      JavaScript: 3,
      MongoDB: 2,
    },
    repos: [
      {
        name: "ResumeRadar_AI",
        description: "A production-ready FastAPI backend for analyzing GitHub profiles and LinkedIn profiles to extract skills, technologies, and project quality.",
        primary_language: "Python",
        topics: ["fastapi", "ai", "github-api", "developer-tools", "pydantic", "developer-profile"],
        last_updated: "2026-03-28T14:22:10Z",
        default_branch: "main",
        readme_first_lines: "# ResumeRadar AI\n\nA production-ready FastAPI backend for analyzing GitHub profiles...",
        analysis: {
          has_description: true,
          has_readme: true,
          multiple_languages: false,
          recently_updated: true,
          has_topics: true,
          has_external_link: true,
          strong_project: true,
        },
      },
      {
        name: "distributed-task-orchestrator",
        description: "Lightweight async event consumer and worker dispatch engine built with Redis streams and Python asyncio.",
        primary_language: "Python",
        topics: ["redis", "asyncio", "distributed-systems", "microservices"],
        last_updated: "2026-02-15T09:12:44Z",
        default_branch: "main",
        readme_first_lines: "# Task Orchestrator\nHigh-throughput worker pool using Redis Streams and asyncio.",
        analysis: {
          has_description: true,
          has_readme: true,
          multiple_languages: false,
          recently_updated: true,
          has_topics: true,
          has_external_link: true,
          strong_project: true,
        },
      },
      {
        name: "cloud-metrics-dashboard",
        description: "Fullstack telemetry observation deck featuring real-time latency heatmaps and server health monitors.",
        primary_language: "TypeScript",
        topics: ["nextjs", "react", "dashboard", "tailwind", "charts"],
        last_updated: "2026-01-20T18:40:02Z",
        default_branch: "main",
        readme_first_lines: "# Cloud Metrics\nNext.js dashboard with responsive telemetry charts.",
        analysis: {
          has_description: true,
          has_readme: true,
          multiple_languages: false,
          recently_updated: true,
          has_topics: true,
          has_external_link: false,
          strong_project: true,
        },
      },
      {
        name: "postgres-query-analyzer",
        description: "Automated slow-query profiling tool that checks EXPLAIN ANALYZE plans and indexes.",
        primary_language: "Python",
        topics: ["postgresql", "database", "query-optimization"],
        last_updated: "2025-11-04T11:05:19Z",
        default_branch: "main",
        readme_first_lines: "# Query Analyzer\nInspect execution plans for PostgreSQL databases.",
        analysis: {
          has_description: true,
          has_readme: true,
          multiple_languages: false,
          recently_updated: true,
          has_topics: true,
          has_external_link: false,
          strong_project: true,
        },
      },
    ],
  },
  linkedin: {
    profile_id: "kaushiksambe",
    total_certifications: 2,
    total_roles: 3,
    certifications: [
      { name: "AWS Certified Developer - Associate", issuer: "Amazon Web Services" },
      { name: "Professional Python Programmer", issuer: "Python Institute" },
    ],
    roles: [
      { title: "Backend Engineer", company: "Kasata" },
      { title: "Software Development Engineer", company: "Cloud Technologies" },
      { title: "Full Stack Developer Intern", company: "NextGen Labs" },
    ],
    access_note: "Structured LinkedIn schema parsed. In production, utilize official LinkedIn API or authorized enterprise OAuth for full synchronization.",
  },
};
