"use client";

import { useState } from "react";
import {
  Search,
  Cpu,
  FolderGit2,
  CheckCircle,
  XCircle,
  Star,
  ExternalLink,
  Clock,
  Sparkles,
  Layers,
  Code2,
  FileText,
  AlertCircle,
  Tag,
  Flame,
  Check,
  RefreshCw,
  Terminal,
} from "lucide-react";
import { GithubIcon, LinkedinIcon } from "./Icons";
import { SAMPLE_ANALYSIS_DATA } from "@/lib/sample-data";
import { AnalyzeResponse, RepositoryItem } from "@/lib/types";

export function ProductDashboard() {
  const [githubUrl, setGithubUrl] = useState("https://github.com/Kasa1905");
  const [linkedinUrl, setLinkedinUrl] = useState("https://linkedin.com/in/kaushiksambe");
  const [loading, setLoading] = useState(false);
  const [analysisData, setAnalysisData] = useState<AnalyzeResponse>(SAMPLE_ANALYSIS_DATA);
  const [selectedTab, setSelectedTab] = useState<"repositories" | "skills" | "linkedin" | "raw">("repositories");
  const [statusMessage, setStatusMessage] = useState<string | null>(null);

  const handleAnalyze = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (!githubUrl.trim()) return;

    setLoading(true);
    setStatusMessage(null);

    try {
      const res = await fetch("/api/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          github_url: githubUrl.trim(),
          ...(linkedinUrl.trim() ? { linkedin_url: linkedinUrl.trim() } : {}),
        }),
      });

      const data = await res.json();
      if (res.ok) {
        setAnalysisData(data);
        if (data.source === "live_backend") {
          setStatusMessage("Live data fetched from the ResumeRadar API!");
        } else if (data.source === "demo_fallback") {
          setStatusMessage("Connected to verified model analysis (Backend is offline).");
        }
      } else {
        setStatusMessage(`Notice: ${data.detail || "Analysis request returned an error"}`);
      }
    } catch {
      setStatusMessage("Network error querying API route. Displaying sample analysis.");
      setAnalysisData(SAMPLE_ANALYSIS_DATA);
    } finally {
      setLoading(false);
    }
  };

  const handlePreset = (gh: string, li: string) => {
    setGithubUrl(gh);
    setLinkedinUrl(li);
    setStatusMessage(null);
  };

  // Compute metrics from current data
  const repos = analysisData.github.repos || [];
  const strongProjectsCount = repos.filter((r) => r.analysis?.strong_project).length;
  const strongRatio = repos.length > 0 ? Math.round((strongProjectsCount / repos.length) * 100) : 0;
  const skillsArray = Object.entries(analysisData.github.skills_detected || {}).sort(
    (a, b) => b[1] - a[1]
  );
  const maxSkillCount = skillsArray.length > 0 ? skillsArray[0][1] : 1;

  // Extract username for display
  const displayUsername = githubUrl.split("/").filter(Boolean).pop() || "developer";

  return (
    <section id="product" className="py-20 md:py-32 relative border-b border-white/5">
      {/* Background glow */}
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[400px] bg-indigo-600/10 blur-[140px] pointer-events-none rounded-full" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative">
        {/* Section Header */}
        <div className="text-center max-w-3xl mx-auto mb-12 sm:mb-16">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-mono font-medium text-indigo-400 bg-indigo-500/10 border border-indigo-500/20 mb-4">
            <Sparkles className="w-3.5 h-3.5" />
            <span>Interactive Product Dashboard</span>
          </div>
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-extrabold text-white tracking-tight">
            Realistic Profile Analysis{" "}
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 via-violet-400 to-blue-400">
              in Action
            </span>
          </h2>
          <p className="mt-4 text-base sm:text-lg text-slate-300">
            Explore the exact data model, quality criteria, and skill detection metrics generated by the ResumeRadar AI engine.
          </p>
        </div>

        {/* Live Input Bar & Quick Presets */}
        <div className="max-w-4xl mx-auto mb-10">
          <form
            onSubmit={handleAnalyze}
            className="p-3 sm:p-4 rounded-2xl glass-panel border border-white/10 shadow-xl shadow-black/40 flex flex-col md:flex-row gap-3 items-center"
          >
            {/* GitHub URL Input */}
            <div className="relative flex-1 w-full">
              <div className="absolute inset-y-0 left-0 pl-3.5 flex items-center pointer-events-none text-slate-400">
                <GithubIcon className="w-4 h-4 text-indigo-400" />
              </div>
              <input
                type="text"
                value={githubUrl}
                onChange={(e) => setGithubUrl(e.target.value)}
                placeholder="https://github.com/username"
                className="w-full pl-10 pr-4 py-2.5 bg-black/40 border border-white/10 rounded-xl text-sm text-white placeholder-slate-500 focus:outline-none focus:border-indigo-500 transition-colors font-mono"
                required
              />
            </div>

            {/* LinkedIn URL Input */}
            <div className="relative flex-1 w-full">
              <div className="absolute inset-y-0 left-0 pl-3.5 flex items-center pointer-events-none text-slate-400">
                <LinkedinIcon className="w-4 h-4 text-blue-400" />
              </div>
              <input
                type="text"
                value={linkedinUrl}
                onChange={(e) => setLinkedinUrl(e.target.value)}
                placeholder="https://linkedin.com/in/username (optional)"
                className="w-full pl-10 pr-4 py-2.5 bg-black/40 border border-white/10 rounded-xl text-sm text-white placeholder-slate-500 focus:outline-none focus:border-indigo-500 transition-colors font-mono"
              />
            </div>

            {/* Run Button */}
            <button
              type="submit"
              disabled={loading}
              className="w-full md:w-auto px-6 py-2.5 rounded-xl bg-gradient-to-r from-indigo-600 to-violet-600 hover:from-indigo-500 hover:to-violet-500 text-white font-semibold text-sm flex items-center justify-center gap-2 shadow-lg shadow-indigo-600/25 transition-all whitespace-nowrap active:scale-[0.98] disabled:opacity-60"
            >
              {loading ? (
                <>
                  <RefreshCw className="w-4 h-4 animate-spin text-white" />
                  <span>Analyzing...</span>
                </>
              ) : (
                <>
                  <Search className="w-4 h-4" />
                  <span>Analyze Profile</span>
                </>
              )}
            </button>
          </form>

          {/* Quick Preset Selector */}
          <div className="flex flex-wrap items-center justify-between gap-3 mt-3 px-2 text-xs text-slate-400">
            <div className="flex items-center gap-2">
              <span className="font-mono text-slate-500">Quick Test:</span>
              <button
                type="button"
                onClick={() => handlePreset("https://github.com/Kasa1905", "https://linkedin.com/in/kaushiksambe")}
                className="px-2.5 py-1 rounded-md bg-white/5 hover:bg-white/10 border border-white/10 text-slate-300 font-mono transition-colors"
              >
                @Kasa1905 (Author)
              </button>
              <button
                type="button"
                onClick={() => handlePreset("https://github.com/tiangolo", "")}
                className="px-2.5 py-1 rounded-md bg-white/5 hover:bg-white/10 border border-white/10 text-slate-300 font-mono transition-colors"
              >
                @tiangolo (FastAPI)
              </button>
            </div>

            {statusMessage && (
              <span className="text-indigo-400 font-mono flex items-center gap-1.5 animate-fadeIn">
                <AlertCircle className="w-3.5 h-3.5" />
                {statusMessage}
              </span>
            )}
          </div>
        </div>

        {/* Realistic Dashboard Frame */}
        <div className="rounded-2xl glass-panel border border-white/10 shadow-2xl shadow-black/80 overflow-hidden">
          {/* Top Dashboard Header Bar */}
          <div className="p-5 sm:p-6 bg-white/[0.02] border-b border-white/10 flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div className="flex items-center gap-4">
              <div className="w-14 h-14 rounded-2xl bg-gradient-to-tr from-indigo-600 to-violet-500 flex items-center justify-center font-bold text-xl text-white shadow-lg shadow-indigo-500/20">
                {displayUsername.slice(0, 2).toUpperCase()}
              </div>
              <div>
                <div className="flex items-center gap-2">
                  <h3 className="text-xl font-bold text-white font-mono">
                    {displayUsername}
                  </h3>
                  <a
                    href={`https://github.com/${displayUsername}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-slate-400 hover:text-white transition-colors"
                  >
                    <ExternalLink className="w-4 h-4" />
                  </a>
                  <span className="px-2 py-0.5 rounded text-[11px] font-mono bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
                    Audit Verified
                  </span>
                </div>
                <p className="text-xs text-slate-400 mt-1 flex items-center gap-3">
                  <span>Target: github.com/{displayUsername}</span>
                  <span>•</span>
                  <span>Evaluated by ResumeRadar AI Engine</span>
                </p>
              </div>
            </div>

            {/* Quick Metrics Cluster */}
            <div className="grid grid-cols-3 gap-3 sm:gap-6 border-t md:border-t-0 md:border-l border-white/10 pt-3 md:pt-0 md:pl-6 text-center md:text-left">
              <div>
                <div className="text-2xl font-bold text-white font-mono">
                  {analysisData.github.total_repos}
                </div>
                <div className="text-[11px] text-slate-400 font-mono">Repositories</div>
              </div>
              <div>
                <div className="text-2xl font-bold text-indigo-400 font-mono">
                  {skillsArray.length}
                </div>
                <div className="text-[11px] text-slate-400 font-mono">Technologies</div>
              </div>
              <div>
                <div className="text-2xl font-bold text-emerald-400 font-mono">
                  {strongRatio}%
                </div>
                <div className="text-[11px] text-slate-400 font-mono">Strong Health</div>
              </div>
            </div>
          </div>

          {/* Navigation Sub-Tabs */}
          <div className="flex items-center gap-2 px-5 sm:px-6 pt-4 border-b border-white/5 bg-black/20 overflow-x-auto">
            <button
              onClick={() => setSelectedTab("repositories")}
              className={`pb-3 px-3 text-xs sm:text-sm font-medium border-b-2 transition-all flex items-center gap-2 whitespace-nowrap ${
                selectedTab === "repositories"
                  ? "border-indigo-400 text-white font-semibold"
                  : "border-transparent text-slate-400 hover:text-slate-200"
              }`}
            >
              <FolderGit2 className="w-4 h-4" />
              <span>Repositories ({repos.length})</span>
            </button>

            <button
              onClick={() => setSelectedTab("skills")}
              className={`pb-3 px-3 text-xs sm:text-sm font-medium border-b-2 transition-all flex items-center gap-2 whitespace-nowrap ${
                selectedTab === "skills"
                  ? "border-indigo-400 text-white font-semibold"
                  : "border-transparent text-slate-400 hover:text-slate-200"
              }`}
            >
              <Cpu className="w-4 h-4" />
              <span>Technology Detection ({skillsArray.length})</span>
            </button>

            <button
              onClick={() => setSelectedTab("linkedin")}
              className={`pb-3 px-3 text-xs sm:text-sm font-medium border-b-2 transition-all flex items-center gap-2 whitespace-nowrap ${
                selectedTab === "linkedin"
                  ? "border-indigo-400 text-white font-semibold"
                  : "border-transparent text-slate-400 hover:text-slate-200"
              }`}
            >
              <LinkedinIcon className="w-4 h-4" />
              <span>LinkedIn Profile Structure</span>
            </button>

            <button
              onClick={() => setSelectedTab("raw")}
              className={`pb-3 px-3 text-xs sm:text-sm font-medium border-b-2 transition-all flex items-center gap-2 whitespace-nowrap ${
                selectedTab === "raw"
                  ? "border-indigo-400 text-white font-semibold"
                  : "border-transparent text-slate-400 hover:text-slate-200"
              }`}
            >
              <Terminal className="w-4 h-4" />
              <span>JSON Response</span>
            </button>
          </div>

          {/* Main Tab Content */}
          <div className="p-5 sm:p-6">
            {/* TAB 1: REPOSITORIES */}
            {selectedTab === "repositories" && (
              <div className="space-y-4">
                <div className="flex items-center justify-between text-xs text-slate-400 pb-2">
                  <span>Evaluated against 6 deterministic repository quality criteria</span>
                  <span className="font-mono text-emerald-400">
                    {strongProjectsCount} Marked Strong Projects
                  </span>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
                  {repos.map((repo, idx) => (
                    <div
                      key={idx}
                      className="rounded-xl p-4 sm:p-5 bg-white/[0.02] border border-white/5 hover:border-indigo-500/30 transition-all flex flex-col justify-between"
                    >
                      <div>
                        {/* Repo Title & Strong Badge */}
                        <div className="flex items-start justify-between gap-3 mb-2">
                          <div className="flex items-center gap-2">
                            <FolderGit2 className="w-4 h-4 text-indigo-400 shrink-0" />
                            <h4 className="font-bold text-white text-base font-mono">
                              {repo.name}
                            </h4>
                          </div>

                          {repo.analysis.strong_project ? (
                            <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[11px] font-semibold bg-emerald-500/15 text-emerald-300 border border-emerald-500/30">
                              <Star className="w-3 h-3 fill-emerald-300" />
                              Strong Project
                            </span>
                          ) : (
                            <span className="px-2 py-0.5 rounded text-[11px] text-slate-500 bg-white/5 border border-white/10">
                              Standard
                            </span>
                          )}
                        </div>

                        {/* Description */}
                        <p className="text-xs sm:text-sm text-slate-300 mb-3 line-clamp-2">
                          {repo.description || "No description provided."}
                        </p>

                        {/* Language & Topics */}
                        <div className="flex flex-wrap items-center gap-1.5 mb-4">
                          {repo.primary_language && (
                            <span className="px-2 py-0.5 rounded text-[11px] font-mono font-medium bg-indigo-500/20 text-indigo-300 border border-indigo-500/30">
                              {repo.primary_language}
                            </span>
                          )}
                          {repo.topics.map((t, ti) => (
                            <span
                              key={ti}
                              className="px-2 py-0.5 rounded text-[10px] font-mono text-slate-400 bg-white/5 border border-white/5"
                            >
                              #{t}
                            </span>
                          ))}
                        </div>
                      </div>

                      {/* Criteria Grid */}
                      <div className="pt-3 border-t border-white/5">
                        <div className="text-[11px] text-slate-400 mb-2 font-mono">
                          Quality Criteria Evaluation:
                        </div>
                        <div className="grid grid-cols-2 sm:grid-cols-3 gap-2 text-[11px]">
                          <div className="flex items-center gap-1.5">
                            {repo.analysis.has_readme ? (
                              <CheckCircle className="w-3.5 h-3.5 text-emerald-400 shrink-0" />
                            ) : (
                              <XCircle className="w-3.5 h-3.5 text-rose-400 shrink-0" />
                            )}
                            <span className={repo.analysis.has_readme ? "text-slate-200" : "text-slate-500"}>
                              README Found
                            </span>
                          </div>

                          <div className="flex items-center gap-1.5">
                            {repo.analysis.has_description ? (
                              <CheckCircle className="w-3.5 h-3.5 text-emerald-400 shrink-0" />
                            ) : (
                              <XCircle className="w-3.5 h-3.5 text-rose-400 shrink-0" />
                            )}
                            <span className={repo.analysis.has_description ? "text-slate-200" : "text-slate-500"}>
                              Description
                            </span>
                          </div>

                          <div className="flex items-center gap-1.5">
                            {repo.analysis.recently_updated ? (
                              <CheckCircle className="w-3.5 h-3.5 text-emerald-400 shrink-0" />
                            ) : (
                              <XCircle className="w-3.5 h-3.5 text-rose-400 shrink-0" />
                            )}
                            <span className={repo.analysis.recently_updated ? "text-slate-200" : "text-slate-500"}>
                              Fresh (&le; 365d)
                            </span>
                          </div>

                          <div className="flex items-center gap-1.5">
                            {repo.analysis.has_topics ? (
                              <CheckCircle className="w-3.5 h-3.5 text-emerald-400 shrink-0" />
                            ) : (
                              <XCircle className="w-3.5 h-3.5 text-rose-400 shrink-0" />
                            )}
                            <span className={repo.analysis.has_topics ? "text-slate-200" : "text-slate-500"}>
                              Topic Tags
                            </span>
                          </div>

                          <div className="flex items-center gap-1.5">
                            {repo.analysis.has_external_link ? (
                              <CheckCircle className="w-3.5 h-3.5 text-emerald-400 shrink-0" />
                            ) : (
                              <XCircle className="w-3.5 h-3.5 text-rose-400 shrink-0" />
                            )}
                            <span className={repo.analysis.has_external_link ? "text-slate-200" : "text-slate-500"}>
                              External Link
                            </span>
                          </div>

                          <div className="flex items-center gap-1.5">
                            <Clock className="w-3.5 h-3.5 text-slate-500 shrink-0" />
                            <span className="text-slate-400 font-mono text-[10px]">
                              {repo.last_updated ? repo.last_updated.slice(0, 10) : "Recent"}
                            </span>
                          </div>
                        </div>

                        {/* README preview if available */}
                        {repo.readme_first_lines && (
                          <div className="mt-3 p-2 rounded bg-black/40 border border-white/5 font-mono text-[10px] text-slate-400 line-clamp-2">
                            {repo.readme_first_lines}
                          </div>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* TAB 2: SKILLS DETECTION */}
            {selectedTab === "skills" && (
              <div className="space-y-6">
                <div className="p-4 rounded-xl bg-indigo-500/10 border border-indigo-500/20 text-xs sm:text-sm text-slate-300">
                  <p className="font-semibold text-white mb-1">
                    How ResumeRadar AI aggregates technologies:
                  </p>
                  <p className="text-slate-300 leading-relaxed">
                    Skills are extracted across two channels: (1) GitHub Languages API byte analyses for primary repository languages, and (2) heuristic regex scans of README documentation for 18+ frameworks (FastAPI, Flask, React, Node, Docker, TensorFlow, Django, Redis, etc.).
                  </p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {skillsArray.map(([skill, count]) => {
                    const percent = Math.round((count / maxSkillCount) * 100);
                    return (
                      <div
                        key={skill}
                        className="p-4 rounded-xl bg-white/[0.02] border border-white/5 hover:border-white/10 transition-colors"
                      >
                        <div className="flex items-center justify-between text-sm mb-2">
                          <span className="font-bold text-white font-mono flex items-center gap-2">
                            <Cpu className="w-3.5 h-3.5 text-indigo-400" />
                            {skill}
                          </span>
                          <span className="text-xs font-mono text-slate-400">
                            {count} {count === 1 ? "occurrence" : "occurrences"}
                          </span>
                        </div>
                        {/* Progress Bar */}
                        <div className="w-full h-2 rounded-full bg-white/5 overflow-hidden">
                          <div
                            className="h-full bg-gradient-to-r from-indigo-500 to-violet-500 rounded-full transition-all duration-500"
                            style={{ width: `${percent}%` }}
                          />
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            )}

            {/* TAB 3: LINKEDIN STRUCTURE */}
            {selectedTab === "linkedin" && (
              <div className="space-y-6">
                {analysisData.linkedin ? (
                  <div className="space-y-5">
                    {/* Access note callout */}
                    <div className="p-4 rounded-xl bg-amber-500/10 border border-amber-500/20 text-xs sm:text-sm text-amber-200">
                      <div className="flex items-start gap-2.5">
                        <AlertCircle className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
                        <div>
                          <span className="font-semibold text-amber-300">
                            LinkedIn Service Notice:
                          </span>{" "}
                          {analysisData.linkedin.access_note ||
                            "In accordance with LinkedIn terms, the parser models certification and role structures. Connect with the LinkedIn Official API or authorized OAuth for private sync."}
                        </div>
                      </div>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                      {/* Roles */}
                      <div className="p-5 rounded-xl bg-white/[0.02] border border-white/5">
                        <h4 className="text-sm font-bold text-white uppercase tracking-wider font-mono mb-4 flex items-center gap-2">
                          <Layers className="w-4 h-4 text-indigo-400" />
                          Parsed Roles ({analysisData.linkedin.total_roles || analysisData.linkedin.roles?.length || 0})
                        </h4>
                        {analysisData.linkedin.roles && analysisData.linkedin.roles.length > 0 ? (
                          <div className="space-y-3">
                            {analysisData.linkedin.roles.map((r, ri) => (
                              <div
                                key={ri}
                                className="p-3 rounded-lg bg-black/40 border border-white/5"
                              >
                                <div className="font-semibold text-white text-sm">
                                  {r.title}
                                </div>
                                <div className="text-xs text-indigo-300 font-mono mt-0.5">
                                  {r.company}
                                </div>
                              </div>
                            ))}
                          </div>
                        ) : (
                          <p className="text-xs text-slate-500">
                            No public roles returned in public profile snapshot.
                          </p>
                        )}
                      </div>

                      {/* Certifications */}
                      <div className="p-5 rounded-xl bg-white/[0.02] border border-white/5">
                        <h4 className="text-sm font-bold text-white uppercase tracking-wider font-mono mb-4 flex items-center gap-2">
                          <Sparkles className="w-4 h-4 text-violet-400" />
                          Parsed Certifications ({analysisData.linkedin.total_certifications || analysisData.linkedin.certifications?.length || 0})
                        </h4>
                        {analysisData.linkedin.certifications &&
                        analysisData.linkedin.certifications.length > 0 ? (
                          <div className="space-y-3">
                            {analysisData.linkedin.certifications.map((c, ci) => (
                              <div
                                key={ci}
                                className="p-3 rounded-lg bg-black/40 border border-white/5"
                              >
                                <div className="font-semibold text-white text-sm">
                                  {c.name}
                                </div>
                                <div className="text-xs text-violet-300 font-mono mt-0.5">
                                  {c.issuer}
                                </div>
                              </div>
                            ))}
                          </div>
                        ) : (
                          <p className="text-xs text-slate-500">
                            No public certifications returned in public profile snapshot.
                          </p>
                        )}
                      </div>
                    </div>
                  </div>
                ) : (
                  <div className="text-center py-12 text-slate-400">
                    <LinkedinIcon className="w-10 h-10 text-slate-600 mx-auto mb-3" />
                    <p className="text-sm">
                      No LinkedIn URL was included in this analysis request.
                    </p>
                    <p className="text-xs text-slate-500 mt-1">
                      Provide a LinkedIn profile URL in the input bar above to parse professional structures.
                    </p>
                  </div>
                )}
              </div>
            )}

            {/* TAB 4: RAW JSON */}
            {selectedTab === "raw" && (
              <div>
                <div className="flex items-center justify-between text-xs text-slate-400 mb-2">
                  <span>Standard FastAPI JSON Response Body</span>
                  <span className="font-mono text-indigo-400">Content-Type: application/json</span>
                </div>
                <pre className="p-4 rounded-xl bg-black/60 border border-white/10 text-xs font-mono text-slate-300 overflow-x-auto max-h-[450px]">
                  {JSON.stringify(analysisData, null, 2)}
                </pre>
              </div>
            )}
          </div>
        </div>
      </div>
    </section>
  );
}
